#include "noahLib.h"
#include "fieldNames.h"

// stolen from https://gamefaqs.gamespot.com/ps/199365-xenogears/faqs/4415

sFieldName fieldNames[] =
{
    {0, "Main debug room"},
    {1, "Lahan village                                                  "},
    {2, "Lahan battle(intro version)                                    "},
    {3, "Outside Lahan - after the battle                               "},
    {4, "Introductory text at the start of the game                     "},
    {5, "Lahan - Beginners hall                                         "},
    {6, "Lahan - Item shop                                              "},
    {7, "Lahan - Rock - Paper - Scissors man                            "},
    {8, "Lahan - RPS man's basement                                     "},
    {9, "Lahan - Pub                                                    "},
    {10, "Lahan - Pub, upstairs                                          "},
    {11, "Lahan - Alice's house                                          "},
    {12, "Lahan - Fei talks to Alice                                     "},
    {13, "Lahan - Fei's house                                            "},
    {14, "Lahan - Looking at Fei's painting                              "},
    {15, "Outside Lahan - Mountain path                                  "},
    {16, "Outside Lahan - Gears fly over Citan's                         "},
    {17, "Citan's House                                                  "},
    {18, "Citan's house - Bedroom                                        "},
    {19, "Citan's house - Kitchen                                        "},
    {20, "Citan's House - Upstairs room                                  "},
    {21, "Citan's House - Workshop (with music box)                      "},
    {22, "Blackmoon Forest Entrance                                      "},
    {23, "Blackmoon Forest - Fei & Elly wake up by tree                  "},
    {24, "Blackmoon Forest - The 'Rankar' opening.T                      "},
    {25, "Blackmoon Forest - Fei and Elly by campfire                    "},
    {26, "Blackmoon Forest - Citan chats with Elly                       "},
    {27, "Elly's Flashback (Flying Weltall)                              "},
    {28, "Elly's Flashback (Crash Landing)                               "},
    {29, "Dazil - Water room                                             "},
    {30, "Dazil - House with gossiping Aveh guards                       "},
    {31, "Dazil - House                                                  "},
    {32, "Dazil - House                                                  "},
    {33, "Dazil - House                                                  "},
    {34, "Dazil - House                                                  "},
    {35, "Dazil - Outside the waterworks                                 "},
    {36, "Dazil - Buggy rental shop                                      "},
    {37, "Dazil - 'Treasure Hunter Association'                          "},
    {38, "Dazil - Aveh Guard station                                     "},
    {39, "Dazil - Scene when Fei and Citan see the dig sites             "},
    {40, "Dazil - 'Lucky Avenue' bar                                     "},
    {41, "Lahan - Id in Weltall(before Fei gets in Weltall)              "},
    {42, "Weird room with 2 red guys(the Dora ? no textures)             "},
    {43, "Dazil - Inn, upstairs                                          "},
    {44, "Dazil - Gear Shop                                              "},
    {45, "Dazil - Ethos Workshop                                         "},
    {46, "Duneman Isle - Top of Sandfall                                 "},
    {47, "Duneman Isle - Bottom of Sandfall Cliffs                       "},
    {48, "Duneman Desert                                                 "},
    {49, "Aveh Desert - UFO(Shevat) flies overhead                       "},
    {50, "Aveh Desert - Bikes ride by, Fei steals one                    "},
    {51, "Duneman Isle - Dino Skeleton                                   "},
    {52, "Duneman Isle - Dino Skeleton(Camera zooms around it)           "},
    {53, "Aveh Desert Entrance                                           "},
    {54, "Aveh Desert - Fei ambushed by 2 gears, Citan brings Weltall    "},
    {55, "Aveh Desert - Fei meets Grahf                                  "},
    {56, "Aveh Transport(Fei's dream about Grahf & Kahn)                 "},
    {57, "Aveh Transport(Near exit)                                      "},
    {58, "Aveh Transport - Second room                                   "},
    {59, "Aveh Transport - Fei climbs the crane to Weltall               "},
    {60, "Aveh Transport hit by Yggdrasil                                "},
    {70, "Bottom of elevator in Stalactite Cavern(just before Calamity)  "},
    {80, "Bart's Hideout - Yggdrasil docking                             "},
    {81, "Bart's Hideout - Maison explains the exacavation of gears      "},
    {82, "Bart's Hideout - Fei fights Vance during Gebler attack         "},
    {83, "Bart's Hideout - Fei, Citan and Bart fight the Schpariel boss  "},
    {84, "Bart's Hideout - Gear hanger                                   "},
    {85, "Nisan - Item shop                                              "},
    {86, "Nisan - House                                                  "},
    {87, "Nisan - Inn                                                    "},
    {88, "Nisan - Town hall                                              "},
    {89, "Nisan - The attack plan map(game hangs)                        "},
    {90, "Nisan - House                                                  "},
    {91, "Nisan - Artist's studio                                        "},
    {92, "Nisan - House                                                  "},
    {93, "Nisan entrance                                                 "},
    {94, "Nisan map                                                      "},
    {95, "Nisan - Cathedral entrance                                     "},
    {96, "Nisan - Secret dock(invisible Yggdrasil)                       "},
    {97, "Nisan - Cathedral library                                      "},
    {98, "Nisan - Cathedral, Sophia's portrait                           "},
    {99, "Nisan - Cathedral, first staircase                             "},
    {100, "Nisan - Cathedral staircase(Margie standing still halfway)     "},
    {101, "Bledavik map                                                   "},
    {102, "South Bledavik entrance                                        "},
    {103, "South Bledavik entrance                                        "},
    {104, "South Bledavik - Inn                                           "},
    {105, "South Bledavik - Inn, sister's room (via window)               "},
    {106, "South Bledavik - Inn, upstairs, next to sister's room          "},
    {107, "South Bledavik - Inn, downstairs room                          "},
    {108, "South Bledavik - Inn, upstairs, southern room                  "},
    {109, "South Bledavik - schemer's house                               "},
    {110, "South Bledavik - schemer's house, upstairs                     "},
    {111, "South Bledavik - Soldier's family house                        "},
    {112, "South Bledavik - Soldier's family house, upstairs              "},
    {113, "South Bledavik - Armor shopkeeper's house                      "},
    {114, "South Bledavik - Armor shop                                    "},
    {115, "South Bledavik - Draft dodger's house                          "},
    {116, "South Bledavik - Cathouse                                      "},
    {117, "South Bledavik - Cathouse, upstairs                            "},
    {118, "South Bledavik - Bar                                           "},
    {119, "South Bledavik - Potion shop                                   "},
    {120, "South Bledavik - Weapon shop                                   "},
    {121, "South Bledavik - Ethos Gear shop                               "},
    {122, "South Bledavik - Gear shop back room                           "},
    {123, "South Bledavik - Bar                                           "},
    {124, "North Bledavik entrance(no tents)                              "},
    {125, "North Bledavik entrance(festival day)                          "},
    {126, "North Bledavik - Games tent                                    "},
    {127, "North Bledavik - Merry Go Pop                                  "},
    {128, "North Bledavik - Whose Balloons                                "},
    {129, "North Bledavik - Mirror of Truth                               "},
    {130, "Bledavik Underground waterways - near - hotel ladder           "},
    {131, "Aveh Castle - tournament sign - up                             "},
    {132, "Aveh Castle - courtyard                                        "},
    {133, "Aveh Castle - waterways exit                                   "},
    {134, "Aveh Castle - waterways exit, Shakhan's trap                   "},
    {135, "Aveh Castle - first floor hall                                 "},
    {136, "Aveh Castle South - 2nd floor west bedroom                     "},
    {137, "Aveh Castle South - 2nd floor east bedroom                     "},
    {138, "Aveh Castle East - Cobra Cracka bedroom                        "},
    {139, "Aveh Castle East - bedroom                                     "},
    {140, "Aveh Castle East - Armory                                      "},
    {141, "Aveh Castle East, 2nd floor - Vanderkaum's room                "},
    {142, "Aveh Castle East, 2nd floor - Minister's room, south           "},
    {143, "Aveh Castle West - kitchen                                     "},
    {144, "Aveh Castle West - mess hall                                   "},
    {145, "Aveh Castle West, 2nd floor - library                          "},
    {146, "Aveh Castle West, 2nd floor - Minister's room, south           "},
    {147, "Bledavik Underground waterways - Aveh Castle ladder            "},
    {148, "Aveh Castle - Tournament fighters' western tent (Joe)          "},
    {149, "Aveh Castle - Tournament fighters' eastern tent (Dan)          "},
    {150, "Aveh Castle - Throne room                                      "},
    {151, "Aveh Castle - Dining room                                      "},
    {152, "Aveh Castle - East Tower corridor                              "},
    {153, "Aveh Castle - Suite                                            "},
    {154, "Aveh Castle - Margie's room                                    "},
    {155, "Aveh Castle - Shakhan's room                                   "},
    {156, "Aveh Castle - Entrance hall                                    "},
    {157, "Aveh Castle - Second floor hall                                "},
    {158, "Aveh Castle - Third floor hall                                 "},
    {159, "Aveh Castle - Fourth floor hall                                "},
    {160, "Aveh Castle - Ramsus & Miang in bed                            "},
    {161, "Aveh Castle - Ramsus' Elru nightmare continued                 "},
    {162, "Aveh Castle, Gebler area - conference room(can't re-enter)     "},
    {163, "Aveh Castle, Gebler area - hallway to airship dock             "},
    {164, "Aveh Castle, Gebler area - hallway entrance                    "},
    {165, "Aveh Castle, Gebler area - Elly's quarters (can't re - enter)  "},
    {166, "Aveh Castle, Gebler area - basement hallway to non - working elevator            "},
    {167, "Aveh Castle, Gebler area - elevator to 3rd floor, basement                       "},
    {168, "Aveh Castle, Gebler area - Gear dock(no escape)                                  "},
    {169, "Aveh Castle, Gebler area - Ramsus gets a message from Hyu, Margie rescued        "},
    {170, "Aveh Castle, Gebler area - In a wall, somewhere(can't do anything)               "},
    {171, "Aveh Castle, Gebler area - big hallway                                           "},
    {172, "Assault on Aveh - Fei at bottom of inside mountain area                   "},
    {173, "Assault on Aveh - Fei at entrance to inside mountain area                 "},
    {174, "Assault on Aveh - Fei attacked by Elly's unit                             "},
    {175, "Assault on Aveh - Fei at bottom of outside mountain area                  "},
    {176, "Assault on Aveh - Elly's 'Drive' flashback                                "},
    {177, "Assault on Aveh - Weltall beats Vierge, 'Drive' wears off                 "},
    {178, "Assault on Aveh - Fei spots target Vanderkaum from mountain peak          "},
    {179, "Assault on Aveh - Ramsus and Miang's destroyer damages the Yggdrasil      "},
    {180, "Assault on Aveh - chasing Vanderkaum's flagship mini-game                 "},
    {181, "Assault on Aveh - chasing Vanderkaum's flagship midpoint                  "},
    {182, "Assault on Aveh - Fei reaches Vanderkaum's flagship                       "},
    {183, "Assault on Aveh - Yggdrasil bridge, Grahf's music (hangs)                 "},
    {184, "Assault on Aveh - Vanderkaum gets in the Dora                             "},
    {185, "Assault on Aveh - Dora breaks out of the flagship                         "},
    {186, "Assault on Aveh - Dora takes out Maitreya's unit                          "},
    {187, "Assault on Aveh - Bart tries to escape from Ramsus' destroyer             "},
    {188, "Assault on Aveh - Id takes out Ramsus' fleet                              "},
    {189, "Assault on Aveh - Sigurd lands the Yggdrasil on Id                        "},
    {190, "Assault on Aveh - Id trashes Ramsus, attacks Bart                         "},
    {191, "Assault on Aveh - Yggdrasil accelerating for jump(hangs)                  "},
    {192, "Assault on Aveh - Miang grabs Ramsus and flees                            "},
    {193, "Assault on Aveh - same as 184 (? )                                        "},
    {194, "Nortune map(before escape)                                                "},
    {195, "Nortune, A block - outside doctor's house                                 "},
    {196, "Nortune, D block - path from A block                                      "},
    {197, "Nortune, D block - riding the train                                       "},
    {198, "Nortune map(after escape)                                                 "},
    {199, "Nortune, D block - 'Baptism' battle                                       "},
    {200, "Nortune, A block - inside doctor's house                                  "},
    {201, "Nortune, A block - doctor's toilet                                        "},
    {202, "Nortune, A block - car house                                              "},
    {203, "Nortune, A block - car house, back room                                   "},
    {204, "Nortune, A block - car house, upstairs                                    "},
    {205, "Nortune, A block - 'Wildcat' bar                                          "},
    {206, "Nortune, A block - armory                                                 "},
    {207, "Nortune, A block - potion shop                                            "},
    {208, "Nortune, A block - house                                                  "},
    {209, "Nortune, Battling Arena reception area                                    "},
    {210, "Nortune, D block - Ethos Room                                             "},
    {211, "Nortune, D block - Battler's house, upstairs                              "},
    {212, "Nortune, D block - Battler's house, closet                                "},
    {213, "Nortune, D block - Fei awakes from dream in Battler's medical rest area   "},
    {214, "Nortune, D block - Battler's house, showers                               "},
    {215, "Nortune, D block - orphanage                                              "},
    {216, "Nortune, D block - orphanage, upstairs                                    "},
    {217, "Nortune, D block - Latina's bar                                           "},
    {218, "Nortune, D block - Latina's bar, upstairs (\"Champ's room\")              "},
    {219, "Nortune, D block - Champ's bedroom                                        "},
    {220, "Nortune, D block - bad location house                                     "},
    {221, "Nortune, Battling Arena - Fei signs up with Rue                           "},
    {222, "Nortune, Battling Arena reception area(after Nortune purge)               "},
    {223, "Nortune, Battling Arena - Fei given Weltall for battling use              "},
    {224, "Nortune, Battling Arena - Fei rescues Rico beginning                      "},
    {225, "Nortune, Battling Arena - Fei rescues Rico end                            "},
    {226, "Nortune Central District - chicken corridor                               "},
    {227, "Nortune Central District - kitchen                                        "},
    {228, "Nortune Central District - warehouse                                      "},
    {229, "Nortune Central District - Rico's childhood flashback                     "},
    {230, "Nortune Central District entrance                                         "},
    {231, "Nortune Central District - main hall                                      "},
    {232, "Nortune Central District - Goliath room                                   "},
    {233, "Nortune Central District - stairwell                                      "},
    {234, "Nortune Central District - Miang gives Sigmund a gate keeper, Fei dreams  "},
    {235, "Nortune Central District - command center                                 "},
    {236, "Nortune Central District - Kaiser's wife's room                           "},
    {237, "Nortune Central District - Kaiser's room                                  "},
    {238, "black screen(hangs)                                                       "},
    {239, "Kislev sewers entrance                                                    "},
    {240, "Kislev sewers - outside locked door                                       "},
    {241, "Kislev sewers - lower level entrance ladder                               "},
    {242, "Kislev sewers - inside locked door, pipe room                             "},
    {243, "Kislev sewers - Fei's childhood dream (after 234)                         "},
    {244, "Nortune Purge - Fei, Citanand Rico witness the beginning of the purge     "},
    {245, "Nortune Purge - Fei encounters Elly's unit                                "},
    {246, "Nortune Purge - Elly's unit encounters Fei                                "},
    {247, "Nortune Purge - Citan helps evacuate Nortune                              "},
    {248, "Nortune Purge - Grahf saves Elly from Hecht explosion                     "},
    {249, "Nortune Purge intro                                                       "},
    {250, "Kislev Gear Dock - Hanger(beneath arena)                                  "},
    {251, "Kislev Gear Dock entrance                                                 "},
    {252, "Kislev Gear Dock - stockroom                                              "},
    {253, "Kislev Gear Dock - warehouse(crate duct junction)                         "},
    {254, "Kislev Gear Dock - factory                                                "},
    {255, "Kislev Gear Dock - office(master key)                                     "},
    {256, "Kislev Gear Dock - stairwell to hangar                                    "},
    {257, "Kislev Gear Dock - hall between factory and office                        "},
    {258, "Kislev Gear Dock - other end of 257                                       "},
    {259, "Kislev Gear Dock - ducts                                                  "},
    {260, "Goliath Factory - first \"ambush room\"                                     "},
    {261, "Goliath Factory - second \"ambush room\"                                    "},
    {262, "Goliath Factory entrance                                                  "},
    {263, "Goliath Factory - conveyor belt switch room                               "},
    {264, "Goliath Factory - hall to 260                                             "},
    {265, "Goliath Factory - 263 after switching conveyor direction                  "},
    {266, "Goliath Factory - middle conveyor belt room                               "},
    {267, "Goliath Factory - conveyor to Fis - 6 room                                "},
    {268, "Goliath Factory - Fis - 6 room                                            "},
    {269, "Goliath Factory - Fei and co.board the Goliath                            "},
    {270, "Goliath - Grahf attacks(Hammer:  \"...MAD SKILLZ ? !\")                     "},
    {271, "Goliath - Bart missile hits Goliath                                       "},
    {272, "Grahf, Ramsusand Miang broken cutscene                                    "},
    {273, "Solaris - Gazel plans the Nortune purge                                   "},
    {274, "Solaris - Gazel reprimands Ramsus after Fei reaches Shevat                "},
    {275, "Assault on Aveh - Id - damaged Yggdrasil sinks, Citan ejected             "},
    {276, "Assault on Aveh - Citan sees Yggdrasil sink, Dora ruin                    "},
    {277, "Assault on Aveh - Citan views the Dora up - close                         "},
    {278, "Assault on Aveh - same as 186                                             "},
    {279, "Goliath - Bart spots Goliath through periscope                            "},
    {280, "Goliath - Yggdrasil surfaces                                              "},
    {281, "Aveh Desert - Yggdrasil rescues Aveh Transport crew                       "},
    {282, "Assault on Aveh - on Yggdrasil, Maison's bar (after omen?  hangs)         "},
    {283, "Assault on Aveh - on Yggdrasil, Bartand Sig discuss return to Aveh Castle "},
    {284, "Assault on Aveh - military briefing, Fei gives promise to Bart            "},
    {285, "Aveh Desert - Bart and co.chew out Margie after rescue from Shakhan       "},
    {286, "Thames - Elly sabotages the Yggdrasil                                     "},
    {287, "Aveh Desert - Bart attacks the Aveh Transport                             "},
    {288, "Yggdrasil - bottom floor                                                  "},
    {289, "Yggdrasil - barracks                                                      "},
    {290, "Yggdrasil - bridge                                                        "},
    {291, "Yggdrasil - gear hanger                                                   "},
    {292, "Yggdrasil - gear shop                                                     "},
    {293, "Yggdrasil - Weltall's stall                                               "},
    {294, "Shevat Battleship - bridge briefing room(disk2 ? hangs)                   "},
    {295, "Yggdrasil - engine room                                                   "},
    {296, "Yggdrasil - Fei and Elly sneak away from Shevat carbon - freeze           "},
    {297, "Yggdrasil - Bart regrets shooting down the Goliath                        "},
    {298, "Yggdrasil - Rico's room                                                   "},
    {299, "Yggdrasil - infirmary                                                     "},
    {300, "Yggdrasil - Elly's room                                                   "},
    {301, "Yggdrasil - Margie's room                                                 "},
    {302, "Yggdrasil - elevator top                                                  "},
    {303, "Yggdrasil - bottom floor, apologize to Elly sequence                      "},
    {304, "Yggdrasil - elevator bottom                                               "},
    {305, "Yggdrasil - world charts(hangs if no cities visited)                      "},
    {306, "Yggdrasil - same as 305                                                   "},
    {307, "Yggdrasil - same as 305                                                   "},
    {308, "Thames - Elly wakes on floating debris after Goliath shot down            "},
    {309, "Thames - on floating debris, Feiand Elly start to 'awaken'                "},
    {310, "Thames - Vierge is recovered                                              "},
    {311, "Thames - Yggdrasil under attack                                           "},
    {312, "Thames - dock                                                             "},
    {313, "Thames - sickbay                                                          "},
    {314, "Thames - bridge                                                           "},
    {315, "Thames - beer hall                                                        "},
    {316, "Thames - deck                                                             "},
    {317, "Thames - screw elevator                                                   "},
    {318, "Thames - supply entrance                                                  "},
    {319, "Thames map                                                                "},
    {320, "Thames - deck, gang minus Fei goes looking for the \"Etone\"                "},
    {321, "Thames - card game                                                        "},
    {322, "Thames - on Gebler destroyer, Dominiaand Miang argue over Elly            "},
    {323, "Thames - Kelvena and Dominia attack the Yggdrasil                         "},
    {324, "Thames - same as 322                                                      "},
    {325, "Thames - on Gebler destroyer, Miang hypnotizes Elly                       "},
    {326, "Orphanage entrance                                                        "},
    {327, "Orphanage - main room                                                     "},
    {328, "Orphanage - Prim's room                                                   "},
    {329, "Orphanage - Billy's room                                                  "},
    {330, "Orphanage - toilet                                                        "},
    {331, "Orphanage - bedroom                                                       "},
    {332, "Orphanage - Billy's flashback                                             "},
    {333, "Ethos Transport - outside, needs mappara or falls off - screen            "},
    {334, "Ethos Transport - battle with Bloody boss                                 "},
    {335, "Ethos Transport - battle with Giant Wels boss                             "},
    {336, "Ethos Transport - room after hallway                                      "},
    {337, "Ethos Transport - freezer, needs mappara or stuck in wall                 "},
    {338, "Ethos Transport entrance                                                  "},
    {339, "Ethos HQ entrance                                                         "},
    {340, "Ethos HQ - upstairs, Etone room 3                                         "},
    {341, "Ethos HQ - Bishop's room (exit to hidden treasure room hangs)             "},
    {342, "Thames - after 360, Gazel(eliminate Ethos), Krelian(Zeboim)               "},
    {343, "Ethos HQ - stairwell to infirmary(hangs)                                  "},
    {344, "Ethos HQ Purge - stairwell with bishop(hangs)                             "},
    {345, "Ethos HQ - stairwell to 341                                               "},
    {346, "Ethos HQ - Billy leads way downstairs to Ethos infirmary                  "},
    {347, "Ethos HQ - upstairs hallway leading to 348                                "},
    {348, "Ethos HQ - upstairs hallway to 340                                        "},
    {349, "Ethos HQ Purge - library                                                  "},
    {350, "Ethos HQ Purge - dining room                                              "},
    {351, "Ethos HQ Purge - kitchen                                                  "},
    {352, "Ethos HQ Purge - infirmary                                                "},
    {353, "Ethos HQ Purge - infirmary hallway                                        "},
    {354, "Ethos HQ Purge - confessional                                             "},
    {355, "Ethos HQ Purge - hallway to 359                                           "},
    {356, "Ethos HQ Purge - prison cell 1                                            "},
    {357, "Ethos HQ Purge - diagonal elevator down at top                            "},
    {358, "Ethos HQ Purge - diagonal elevator down at bottom                         "},
    {359, "Ethos HQ Purge - Ethos = Solaris data room(hangs)                         "},
    {360, "Ethos HQ Purge - Alkanshel Rises(Stone heads for dig site)                "},
    {361, "Ethos Dig Site entrance                                                   "},
    {362, "Ethos Dig Site - diagonal elevator down at bottom                         "},
    {363, "Ethos Dig Site - room between diagonal and vertical elevators             "},
    {364, "Ethos Dig Site - Miang urges Grahf to help Stein steal Emeralda           "},
    {365, "Ethos Dig Site - vertical elevator(hangs)                                 "},
    {366, "Thames - Krelian's fishbowl after Thames attack                           "},
    {367, "Ethos Dig Site - nanomachine decontamination hallway 1                    "},
    {368, "Ethos Dig Site - hallway after 367                                        "},
    {369, "Ethos Dig Site - inactive control room 1                                  "},
    {370, "Ethos Dig Site - stairwell 1 top                                          "},
    {371, "Ethos Dig Site - nanomachine decontamination hallway 2                    "},
    {372, "Ethos Dig Site - hallway after 371                                        "},
    {373, "Ethos Dig Site - inactive control room 2                                  "},
    {374, "Ethos Dig Site - memory cube room                                         "},
    {375, "Ethos Dig Site - stairwell 2 top                                          "},
    {376, "Ethos Dig Site - nanomachine decontamination airlock                      "},
    {377, "Ethos Dig Site - hall after 376                                           "},
    {378, "Ethos Dig Site - nanoreactor control room                                 "},
    {379, "Ethos Dig Site - hall to Emeralda's room (Elly's flashback ? )            "},
    {380, "Ethos Dig Site - Yggdrasil infirmary, Fei's short Zeboim flashback        "},
    {381, "Ethos Dig Site - Yggdrasil infirmary, end of 380, Id awakens              "},
    {382, "Ethos Dig Site - outside vertical elevator bottom                         "},
    {383, "Ethos Dig Site - walkway over Zeboim(hangs)                               "},
    {384, "Ethos Dig Site - other end of 377                                         "},
    {385, "Ethos Dig Site - hallway before 384                                       "},
    {386, "Ethos Dig Site - vertical elevator bottom                                 "},
    {387, "Ethos Dig Site - stairwell 2 bottom                                       "},
    {388, "Ethos Dig Site - Stein and Grahf, Alkanshel battle                        "},
    {389, "Lighthouse - Emeralda, very end of Zeboim Christmas flashback             "},
    {390, "Lighthouse - \"pure life\", middle of Zeboim Christmas flashback            "},
    {391, "Lighthouse - convenience store                                            "},
    {392, "Lighthouse - convenience store, upstairs                                  "},
    {393, "Lighthouse - Joe's shop!                                                  "},
    {394, "Lighthouse - stairs to upstairs news archive room                         "},
    {395, "Lighthouse - television station downstairs                                "},
    {396, "Lighthouse - Zeboim town square(Emeralda in party)                        "},
    {397, "Lighthouse - Zeboim subway end                                            "},
    {398, "Lighthouse - Zeboim subway begin                                          "},
    {399, "Lighthouse - Zeboim subway middle                                         "},
    {400, "Lighthouse - entire Zeboim Christmas flashback                            "},
    {401, "Lighthouse - restaurant, middle of Zeboim Christmas flashback             "},
    {402, "Lighthouse entrance                                                       "},
    {403, "Lighthouse - elevator bottom                                              "},
    {404, "Lighthouse - elevator down                                                "},
    {405, "Babel Tower entrance                                                      "},
    {406, "Babel Tower - entrance ramp                                               "},
    {407, "Babel Tower - relay station                                               "},
    {408, "Babel Tower - relay station control room                                  "},
    {409, "Babel Tower - handrail room                                               "},
    {410, "Babel Tower - Babel Tower tram                                            "},
    {411, "Babel Tower - outer wall(hangs, no Ramsus)                                "},
    {412, "Babel Tower Ducts - inside from the mirror ledge                          "},
    {413, "Babel Tower Ducts - long corridor 1                                       "},
    {414, "Babel Tower Ducts - long corridor 2                                       "},
    {415, "Babel Tower Ducts - short \"conduit - stairs\" corridor                     "},
    {416, "Babel Tower Ducts - circular platform room                                "},
    {417, "Babel Tower - lock / mirror control room                                  "},
    {418, "Babel Tower - floating platform(enemies) area                             "},
    {419, "Babel Tower - same as 418                                                 "},
    {420, "Babel Tower - top(Seibzehn battle)                                        "},
    {421, "Babel Tower - walking on the clouds ?                                     "},
    {422, "Babel Tower - tram ride                                                   "},
    {423, "Shevat map                                                                "},
    {424, "Shevat City entrance                                                      "},
    {425, "Shevat City - donut - shaped room inside first elevator                   "},
    {426, "Shevat City - inside 425. elevator bottom                                 "},
    {427, "Shevat City - below 426                                                   "},
    {428, "Shevat City - sage's secret room                                          "},
    {429, "Shevat City - Deep Sea Bros bar                                           "},
    {430, "Shevat City - Chu - Chu room                                              "},
    {431, "Shevat City - fisherman's fountain                                        "},
    {432, "Shevat City - mirror room                                                 "},
    {433, "Shevat City - mirror room, upstairs                                       "},
    {434, "Shevat City - child's memorial                                            "},
    {435, "Shevat City - kitchen                                                     "},
    {436, "Shevat City - gear shop                                                   "},
    {437, "Shevat Dock - elevator room                                               "},
    {438, "Shevat Dock - elevator shaft(hangs)                                       "},
    {439, "Shevat Dock - hallway to Seibzehn dock                                    "},
    {440, "Shevat Dock - Yggdrasil / gear dock                                       "},
    {441, "Shevat Dock - Seibzehn dock                                               "},
    {442, "Shevat Attacked - walking on clouds ? (Achtzehn battle, hangs)            "},
    {443, "Shevat Attacked - Seibzehn launch(Achtzehn battle, hangs)                 "},
    {444, "Shevat Attacked - emergency shaft hallway 1 (start)                       "},
    {445, "Shevat Attacked - emergency shaft elevator 1                              "},
    {446, "Shevat Attacked - emergency shaft stairwell 1                             "},
    {447, "Shevat Attacked - emergency shaft hallway 2                               "},
    {448, "Shevat Attacked - emergency shaft elevator 2                              "},
    {449, "Shevat Attacked - emergency shaft elevator 3                              "},
    {450, "Shevat Attacked - outdoor emergency shaft(stuck near savepoint)           "},
    {451, "Shevat Palace - elevator top                                              "},
    {452, "Shevat Palace - hallway to Queen Zephyr's throne                          "},
    {453, "Shevat Palace - throne room                                               "},
    {454, "Shevat Palace - Zephyr, Wisemanand Gaspar discuss deja vu                 "},
    {455, "Shevat Palace - Zephyr's personal chambers                                "},
    {456, "Shevat Palace - bottom of Zephyr's tower                                  "},
    {457, "Shevat Palace - hallway to Shevat prison                                  "},
    {458, "Shevat Palace - hallway to carbon freeze and \"Miang cage\"                 "},
    {459, "Shevat Palace - science lab(Krelian and limiters)                         "},
    {460, "Shevat Palace - 'tactical command room'                                   "},
    {461, "Shevat Palace - library(days of ruin)                                     "},
    {462, "Shevat Palace - barracks(Khan)                                            "},
    {463, "Shevat Palace - gabby old person's room (Zephyr)                          "},
    {464, "Shevat Palace - Balthazar's friends (Maria)                               "},
    {465, "Shevat Palace - historians(Mahanon)                                       "},
    {466, "Shevat Palace - party rest area                                           "},
    {467, "Shevat Palace - prison                                                    "},
    {468, "Shevat Palace - carbon freeze                                             "},
    {469, "Shevat Palace - \"Miang cage\"                                              "},
    {470, "Shevat Palace - mess(Yui in kitchen)                                      "},
    {471, "Shevat Palace - food storeroom                                            "},
    {472, "Shevat Palace - elevator emergency shaft entrance(hangs)                  "},
    {473, "Shevat Palace - Zephyr's throne, Achtzehn briefing (no battle)            "},
    {474, "Occupied Nisan entrance                                                   "},
    {475, "Mausoleum entrance                                                        "},
    {476, "Mausoleum - stairwell                                                     "},
    {477, "Mausoleum - main door                                                     "},
    {478, "Mausoleum - main hall                                                     "},
    {479, "Mausoleum - elevator up                                                   "},
    {480, "Ft.Jasper - elevator 1 corridor                                           "},
    {481, "Ft.Jasper - angel door                                                    "},
    {482, "Ft.Jasper - control room                                                  "},
    {483, "Ft.Jasper - atop(in gears)                                                "},
    {484, "Ft.Jasper - elevator bottom                                               "},
    {485, "Ft.Jasper - elevator 2 corridor                                           "},
    {486, "Ft.Jasper - L - shaped hallway to Omnigear hanger                         "},
    {487, "Ft.Jasper - Jasper lock 2                                                 "},
    {488, "Ft.Jasper - Omnigear hanger                                               "},
    {489, "Desert FMV - beeps and doesn't play cutscene (disk2?)                     "},
    {490, "Title Screen                                                              "},
    {491, "Ft.Jasper - Omnigear bay                                                  "},
    {492, "Ft.Jasper - big round room, upstairs                                      "},
    {493, "Mahanon - in Nisan, Ellyand Margie talk about the pendant                 "},
    {494, "Gate Generator 1 - treasure chest area(hangs)                             "},
    {495, "Gate Generator 1 - Shakhan battle                                         "},
    {496, "Sargasso Point                                                            "},
    {497, "Sargasso Point                                                            "},
    {498, "Sargasso Point - before first Y                                           "},
    {499, "Sargasso Point                                                            "},
    {500, "Sargasso Point - at strong current Y                                      "},
    {501, "Sargasso Point - treasure chest area 1                                    "},
    {502, "Sargasso Point - room before 505                                          "},
    {503, "Sargasso Point - strong current off                                       "},
    {504, "Sargasso Point - treasure chest area 2 (current switch)                   "},
    {505, "Gate Generator 3 - Crescens battle                                        "},
    {506, "Solaris - the now - visible Solaris opens defensively                     "},
    {507, "Krelian's Lab - Krelian examines Elly                                     "},
    {508, "Etrenank Soylent - conference room 1                                      "},
    {509, "Etrenank - outside immigration office                                     "},
    {510, "Etrenank - sewer chase                                                    "},
    {511, "Solaris - Seibzehn carries Fei, Ellyand Citan to Solaris                  "},
    {512, "Etrenank - Samson waiting room                                            "},
    {513, "Etrenank - past the first security scanner                                "},
    {514, "Etrenank - the \"dedication ceremony\", Fei remembers Krelian               "},
    {515, "Aveh Transport - Cain and Citan discuss 'the time of the gospel'          "},
    {516, "Solaris - site of Elly's parents' deaths                                  "},
    {517, "Solaris - bridge after 516 (hangs)                                        "},
    {518, "Solaris - like 514 but hangs                                              "},
    {519, "Solaris, 3rd - Class main causeway                                        "},
    {520, "Solaris, 3rd - Class - quarters with the savepoint                        "},
    {521, "Solaris, 3rd - Class - mutant's quarters (one time)                       "},
    {522, "Solaris, 3rd - Class - empty quarters                                     "},
    {523, "Solaris, 3rd - Class - coward's quarters                                  "},
    {524, "Solaris, 3rd - Class - Elly's hiding place                                "},
    {525, "Solaris, 3rd - Class - garbage chute entrance(Elly's parents)             "},
    {526, "Solaris - labyrinth between 3rd - Class and Etrenank                      "},
    {527, "Etrenank - second security scanner                                        "},
    {528, "Etrenank - immigration office                                             "},
    {529, "Etrenank - \"dedication ceremony\" area(hangs)                              "},
    {530, "Etrenank - ticket office                                                  "},
    {531, "Etrenank - flying gear apartment(Tifa poster)                             "},
    {532, "Etrenank - generous lady's apartment (tickets)                            "},
    {533, "Etrenank - Joe's apartment                                                "},
    {534, "Etrenank - brainwashed guy's apartment (memory cube)                      "},
    {535, "Etrenank - ground floor of apartments                                     "},
    {536, "Etrenank - apartments elevator top                                        "},
    {537, "Etrenank - hangs                                                          "},
    {538, "Etrenank - Elly's house, foyer                                            "},
    {539, "Etrenank - Elly's house, living room                                      "},
    {540, "Etrenank - Elly's house, kitchen and dining area                          "},
    {541, "Etrenank - Elly's house, Erich's room                                     "},
    {542, "Etrenank - Elly's house, Elly's room                                      "},
    {543, "Etrenank - Elly's house                                                   "},
    {544, "Etrenank - garbage chute                                                  "},
    {545, "Etrenank - garbage shredder                                               "},
    {546, "Etrenank - garbage chute ladder                                           "},
    {547, "Etrenank - \"food\" storage area                                            "},
    {548, "Etrenank - hallway to 547                                                 "},
    {549, "Etrenank Soylent - code room                                              "},
    {550, "Etrenank Soylent - foreign object scanner control room                    "},
    {551, "Etrenank Soylent entrance                                                 "},
    {552, "Etrenank Soylent - Citan explains about the 'M Plan' (Erich, Nikolai)     "},
    {553, "Etrenank Soylent - diagonal elevator bottom                               "},
    {554, "Etrenank Soylent - diagonal elevator top                                  "},
    {555, "Krelian's Lab entrance                                                    "},
    {556, "Krelian's Lab - short corridor                                            "},
    {557, "Krelian's Lab - inclined T corridor                                       "},
    {558, "Krelian's Lab - short side corridor                                       "},
    {559, "Krelian's Lab - wide corridor between caged Wels                          "},
    {560, "Krelian's Lab - inclined corridor, locked door                            "},
    {561, "Krelian's Lab - upstairs 555, wide corridor after red doors               "},
    {562, "Krelian's Lab - wide corridor before Wels surgery                         "},
    {563, "Krelian's Lab - wide corridor with memory cube                            "},
    {564, "Krelian's Lab - corridor before nanomachine scanning rings                "},
    {565, "Krelian's Lab - T corridor to musical locked door                         "},
    {566, "Krelian's Lab - long corridor SE to Citan's door                          "},
    {567, "Krelian's Lab - Wels surgery                                              "},
    {568, "Krelian's Lab - room with cage of many Wels                               "},
    {569, "Krelian's Lab - Wels specimon room                                        "},
    {570, "Krelian's Lab - first Wels room                                           "},
    {571, "Krelian's Lab - second Wels room                                          "},
    {572, "Krelian's Lab - Solaris Omnigear observation room                         "},
    {573, "Krelian's Lab - computer room 1                                           "},
    {574, "Krelian's Lab - memory cube room                                          "},
    {575, "Krelian's Lab - conference room 2                                         "},
    {576, "Krelian's Lab - anima alignment lab 1                                     "},
    {577, "Krelian's Lab - anima alignment lab 2                                     "},
    {578, "Krelian's Lab - corridor after 563                                        "},
    {579, "Krelian's Lab - interrogation room                                        "},
    {580, "Krelian's Lab - hologram room                                             "},
    {581, "Krelian's Lab - \"drill\" 1                                                 "},
    {582, "Krelian's Lab - \"drill\" 2                                                 "},
    {583, "Krelian's Lab - \"drill\" 3                                                 "},
    {584, "Krelian's Lab - ramp 1                                                    "},
    {585, "Krelian's Lab - ramp 2                                                    "},
    {586, "Krelian's Lab - ramp 3                                                    "},
    {587, "Krelian's Lab - Merkava hologram room                                     "},
    {588, "Krelian's Lab - animus test area 1                                        "},
    {589, "Krelian's Lab - Malakh Angel growth samples                               "},
    {590, "Krelian's Lab - nanomachine scanning rings                                "},
    {591, "Krelian's Lab - interrogation room rescue                                 "},
    {592, "Krelian's Lab - corridor from Krelian's private lab                       "},
    {593, "Krelian's Lab - Citan blows the last gate generator                       "},
    {594, "Krelian's Lab - corridor to Krelian's private lab                         "},
    {595, "Krelian's Lab - Krelian's private lab                                     "},
    {596, "Krelian's Lab - the rendezvous point                                      "},
    {597, "Krelian's Lab - corridor SE from 596                                      "},
    {598, "Krelian's Lab - corridor SW from 596                                      "},
    {599, "Krelian's Lab - useless corridor                                          "},
    {600, "Krelian's Lab - +-shaped corridor                                         "},
    {601, "Krelian's Lab - corridor after first landmark                             "},
    {602, "Krelian's Lab - second landmark                                           "},
    {603, "Krelian's Lab - animus test area 2                                        "},
    {604, "Krelian's Lab - computer room 2                                           "},
    {605, "Krelian's Lab - conference room 3                                         "},
    {606, "Krelian's Lab - black room (hang)                                         "},
    {607, "Solaris - Hammer tries to kidnap Elly                                     "},
    {608, "Solaris - Id awakens                                                      "},
    {609, "Solaris - red Weltall arrives at Solaris                                  "},
    {610, "Solaris - Citan tells Elly about Id                                       "},
    {611, "Solaris - Id attacks Yggdrasil, Elly stops him(long scenes follow)        "},
    {612, "Taura's House - the all-new, improved, Weltall-2                          "},
    {613, "Taura's House - Ramsus' Omnigear pursues Fei and Elly                     "},
    {614, "Taura's House - outside                                                   "},
    {615, "Taura's House - Citan shows up                                            "},
    {616, "Taura's House - nanoreactor room                                          "},
    {617, "Taura's House - Fei's dream                                               "},
    {618, "Nortune - Yggdrasil IV versus Ft.Hurricane                                "},
    {619, "Mahanon - Razael's Tree                                                   "},
    {620, "Ignas Soylent System - partway into 621 cutscene                          "},
    {621, "Ignas Soylent System - Krelian's key infects the limiter-breaking nanomachines   "},
    {622, "Ignas Soylent System - Sufal Mass battle                                         "},
    {623, "Ignas Soylent System - further into 621 cutscene                                 "},
    {624, "Ignas Soylent System - still further into 621 cutscene                           "},
    {625, "Ignas Soylent System - Sufal Mass, near end of 621 cutscene                      "},
    {626, "Ignas Soylent System - cutscene AGAIN, starts somewhere between 624and 625       "},
    {627, "Anima Relic 1 - Elements combine and attack                               "},
    {628, "Anima Relic 1 entrance                                                    "},
    {629, "Anima Relic 1 - fuse room                                                 "},
    {630, "Anima Relic 1 - door lock B control room                                  "},
    {631, "Anima Relic 1 - central elevator control room                             "},
    {632, "Anima Relic 1 - main hallway                                              "},
    {633, "Anima Relic 1 - secondary hallway                                         "},
    {634, "Anima Relic 1 - big round room                                            "},
    {635, "Anima Relic 1 - big round ABCD - code room                                "},
    {636, "Anima Relic 1 - corridor with sealed doors                                "},
    {637, "Anima Relic 1 - bottom of big round elevator shaft                        "},
    {638, "Anima Relic 1 - Anima Relic room(Billy)                                   "},
    {639, "Anima Relic 2 - corridor with sealed doors                                "},
    {640, "Anima Relic 2 - Anima Relic room(Rico)                                    "},
    {641, "Anima Relic 2 entrance                                                    "},
    {642, "Anima Relic 2 - same as 641, except with pillar bridged gap               "},
    {643, "Anima Relic 2 - three holes room                                          "},
    {644, "Anima Relic 2 - water chasm                                               "},
    {645, "Anima Relic 2 - corridor to pit trap room                                 "},
    {646, "Anima Relic 2 - pit trap room                                             "},
    {647, "Anima Relic 2 - spike room                                                "},
    {648, "Anima Relic 2 - water control room                                        "},
    {649, "Anima Relic 2 - return corridor                                           "},
    {650, "Anima Relic 2 - after 651 (memory cube, Hammer ambush)                    "},
    {651, "Anima Relic 2 - same as 644 minus water                                   "},
    {652, "Mahanon - entering the 10, 000 year old Eldridge                          "},
    {653, "Mahanon - later in 652 cutscene                                           "},
    {654, "Mahanon - later in 652 cutscene, Deus battle                              "},
    {655, "Mahanon - Razael's Tree                                                   "},
    {656, "Mahanon - Grahf gloats over the defeated Fei                              "},
    {657, "Golgoda - Krelian tests Elly                                              "},
    {658, "Shevat - Id shows Fei the Lacan memories(THE long cutscene)               "},
    {659, "Point of Sephirot - Fei's friends interrupt Id's 'contact'                "},
    {660, "Point of Sephirot - birth of the pre - Xenogears                          "},
    {661, "Point of Sephirot - later in 660 cutscene                                 "},
    {662, "Point of Sephirot - Id shows Fei the childhood memories                   "},
    {663, "Point of Sephirot - later in 662 cutscene                                 "},
    {664, "Point of Sephirot - still later in 662, the death of Karen                "},
    {665, "Point of Sephirot - still later in 662, the room of the coward(disk2)     "},
    {666, "Point of Sephirot - end of 662 cutscene, Weltall->Xenogears               "},
    {667, "Point of Sephirot - late in 662, after 665, Feiand Elly thru the ages     "},
    {668, "Point of Sephirot - late in 662, after 667, Fei meets Wave Existence      "},
    {669, "Point of Sephirot - after 666, Fei talks about Kadomony                   "},
    {670, "Etrenank - Lacan painting Sophia                                          "},
    {671, "Etrenank - Krelian takes Lacan to get pigments                            "},
    {672, "Etrenank - Krelian talks about Melchior                                   "},
    {673, "Taura's House - Krelian meets Karen/Miang, before 613                     "},
    {674, "Shevat - after 658, Roniand the gang                                      "},
    {675, "Shevat - unused scene ? Sophia and sisters commission a portrait          "},
    {676, "Shevat - unused scene ? dialogue slightly different from 675              "},
    {677, "Shevat - Krelian curses the Solarian enemy                                "},
    {678, "Shevat - Krelian shows concern for Sophia                                 "},
    {679, "Shevat - Sophia hears Lacan talking to himself                            "},
    {680, "Shevat - Miang posing as Elly in Shevat Prison                            "},
    {681, "Shevat - Lacan finds the point of Sephirot                                "},
    {682, "Shevat - Krelian loses faith                                              "},
    {683, "Shevat - Sophia's suicide attack on Solaris                               "},
    {684, "Shevat - Wiseman leaves Fei with Chief Lee                                "},
    {685, "Snowfield Hideout - abandoned Chu - chu room                              "},
    {686, "Snowfield Hideout - command center                                        "},
    {687, "Snowfield Hideout - rest / save area                                      "},
    {688, "Snowfield Hideout - Y - room, to mirrorand penguins                       "},
    {689, "Snowfield Hideout - hall to prison corridor                               "},
    {690, "Snowfield Hideout - prison corridor(jumps to carbon freeze)               "},
    {691, "Snowfield Hideout - hall to command center                                "},
    {692, "Snowfield Hideout - snowy hall                                            "},
    {693, "Snowfield Hideout - hall to 701                                           "},
    {694, "Snowfield Hideout - gold - diggin jukebox man                             "},
    {695, "Snowfield Hideout - big round main room                                   "},
    {696, "Snowfield Hideout - carbon freeze room                                    "},
    {697, "Snowfield Hideout - Midori and Dan                                        "},
    {698, "Snowfield Hideout - prison                                                "},
    {699, "Snowfield Hideout - mirror room(elevator to 685)                          "},
    {700, "Snowfield Hideout - Zephyr's Tower                                        "},
    {701, "Snowfield Hideout - path to swordsmith                                    "},
    {702, "Merkava - outside entrance                                                "},
    {703, "Merkava - inside entrance                                                 "},
    {704, "Merkava - ledge over 1st laser tunnel to 706                              "},
    {705, "Merkava - 2nd laser tunnel leading to 709                                 "},
    {706, "Merkava - platform puzzle start                                           "},
    {707, "Merkava - tunnels north of puzzle room                                    "},
    {708, "Merkava - tunnels west of puzzle room                                     "},
    {709, "Merkava - angel room adjacent to 710                                      "},
    {700, "Snowfield Hideout - Zephyr's Tower                                        "},
    {710, "Merkava - Ramsus waiting for Fei in Merkava.                              "},
    {711, "Merkava - after beating Ramsus.                                           "},
    {712, "Merkava - Confronting Krelian and Miang.                                  "},
    {713, "Merkava - seconds before fighting Opiomorph.                              "},
    {714, "Merkava - just after Elly shoots Fei.                                     "},
    {715, "Merkava - Room leading to the repairbot in the final dungeon.             "},
    {716, "Merkava - Repairbot at the end of the final dungeon.                      "},
    {717, "Merkava - The inner chamber, about to fight Deus.                         "},
    {718, "Ending - Fei persuing the destructing Deus.                               "},
    {719, "Ending - Talking to Krelian before fighting Urobolus.                     "},
    {720, "Debug room - Kato                                                         "},
    {721, "Debug room - Eto                                                          "},
    {722, "Debug room - Kazoumi                                                      "},
    {723, "Debug room - Suzuki                                                       "},
    {724, "Debug room - Tane                                                         "},
    {725, "Debug room - Koumoto                                                      "},
    {726, "Debug room - Kigoshi                                                      "},
    {727, "Debug room - Uchimichi                                                    "},
    {728, "Debug room - Saito                                                        "},
    {729, "Debug room - Matu                                                         "},

    {-1, nullptr}
};